---
output: github_document
---

Welcome to the course **Data Analytics for Pharmaceutical Sciences**. These documents were prepared by [Dominique-Laurent Couturier](https://github.com/dlc48), [Stéphane Guerrier](https://stephaneguerrier.com/), Wenfei Chu and [Yuming Zhang](https://github.com/Yuming-Zhang).

# Course materials

The linked slides (below) are `.html` files that will only work properly if you are connected to the internet. If you're going off grid, grab the PDFs. You'll miss out on gifs and videos, but the rest will still show up.

*Note:* The slides were created with [`xaringan`](https://github.com/yihui/xaringan/wiki) in [R](cran.r-project.org) and the [template](https://github.com/edrubin/EC607S20) is based on the work of [Ed Rubin](https://edrub.in)

**[Part I: Introduction to Statistical Inference](https://raw.githack.com/stephaneguerrier/data_analytics/master/Lecture1.html)**  (note formats: [.html](https://raw.githack.com/stephaneguerrier/data_analytics/master/Lecture1.html) | .pdf (coming soon 🚧) | [.Rmd](https://raw.githack.com/stephaneguerrier/data_analytics/master/Lecture1.Rmd))

**Part II: ANOVA** (coming soon 🚧)

**Part III: Linear Regression** (coming soon 🚧)

**Part IV: Logistic Regression** (coming soon 🚧)

**Part V: Generalized Additive Model** (coming soon 🚧)
